CREATE TABLE [dbo].[ArticleContent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[ArticleId] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[Content] [nvarchar](MAX) NULL,
	CONSTRAINT [Pk_ArticleContent_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ArticleContent]  ADD  CONSTRAINT [Fk_ArticleContent_ArticleId] FOREIGN KEY([ArticleId])
REFERENCES [dbo].[Article] ([Id])
GO

ALTER TABLE [dbo].[ArticleContent] CHECK CONSTRAINT [Fk_ArticleContent_ArticleId]
GO